# 47 에러 처리

## 47.1 에러 처리의 필요성

에러가 발생하지 않는 코드를 작성하는 것은 불가능하다. 에러는 언제든 발생할 수 있으며, 발생한 에러에 대해 대처하지 않고 방치하면 프로그램은 종료한다. 따라서 개발자라면 항상 에러 처리에 신경을 써야 한다.

보통 단축 평가 또는 옵셔널 체이닝 연산자를 사용하거나 `try...catch` 문을 사용하기도 한다.

<br>

## 47.2 try...catch...finally문

기본적으로 에러 처리를 구현하는 방법은 크게 두 가지가 있다. 예외적인 상황이 발생하면 반환하는 값(`null` 또는 -1 등)을 `if`문이나 단축 평가 또는 옵셔널 체이닝 연산자를 통해 확인해서 처리하는 방법과 `try...catch...finally`문과 같이 에러 처리 코드를 미리 등록해 두고 에러가 발생하면 에러 처리 코드로 점프하도록 하는 방법이 있다. 일반적인 에러 처리(error handling)라고 하면 `try...catch...finally`문의 사용하는 방법을 말한다.

<br>

```javascript
try {
  // 실행할 코드(에러가 발생할 가능성이 있는 코드)
} catch (err) {
  // try 코드 블록에서 에러가 발생하면 이 코드 블록의 코드가 실행된다.
  // err에는 try 코드 블록에서 발생한 Error 객체가 전달된다.
} finally {
  // 에러 발생과 상관없이 반드시 하나 번 실행된다.
}
```

<br>

- `try...catch...finally`문을 실행하면 `try` 코드 블록이 먼저 실행된다.

- 이때 에러가 발생하면 발생한 에러는 `catch` 문의 `err` 변수에 전달되고 `catch` 코드 블록이 실행된다. `catch` 문의 `err` 변수(변수 이름은 무엇이든 상관없지만 보통 `err`, `error`를 쓴다.)는 `try` 코드 블록에 포함된 문 중에서 에러가 발생하면 생성되고 `catch` 코드 블록에서만 유효하다.

- `finally` 코드 블록은 에러 발생과 상관없이 반드시 한 번 실행된다.

<br>

## 47.3 Error 객체

`Error` 생성자 함수는 에러 객체를 생성한다. 그리고 `Error` 생성자 함수에는 에러를 설명하는 메세지를 인수로 전달할 수 있다.

```javascript
const error = new Error('유효하지 않은 값입니다.');
```

<br>

자바스크립트는 `Error` 생성자 함수를 포함해 7가지의 에러 객체를 생성할 수 있는 `Error` 생성자 함수를 제공한다. 이때 생성된 에러 객체의 프로토타입은 모두 `Error.prototype`을 상속받는다.

<br>

![](https://velog.velcdn.com/images/wlals4264/post/afa291f9-b16d-4927-adef-6ac187f7f730/image.png)

<br>

## 47.4 throw 문

`Error` 생성자 함수로 에러 객체를 생성한다고 에러가 발생하는 것은 아니다. 즉, 에러 객체 생성과 에러 발생은 의미가 다르다.

에러를 발생시키려면 `try` 코드 블록에서 `throw` 문으로 에러 객체를 던져야 한다.

<br>

```javascript
throw 표현식;
```

<br>

`throw` 문의 표현식은 어떤 값이라도 상관없지만 보통 일반적으로 에러 객체를 지정한다. 에러를 던지면 `catch`문의 에러 변수가 생성되고 던져진 에러 객체가 할당된다. 그리고 `catch` 코드 블록이 실행되기 시작한다.

<br>

```javascript
try {
  // 에러 객체를 던지면 catch 코드 블록이 실행되기 시작한다.
  throw new Error('something wrong');
} catch (error) {
  console.log(error);
}
```

<br>

![](https://velog.velcdn.com/images/wlals4264/post/29a6c731-d3d4-445b-bb5a-138b7102727d/image.png)

<br>

## 47.5 에러의 전파

앞서 프로미스에서 에러 처리의 한계에서 살펴봤듯이 에러는 호출자 방향으로 전파된다. 다음 예제에서 `throw`된 에러는 호출자 방향으로 전파되어 전역에서 `catch` 된다.

<br>

```javascript
const foo = () => {
  throw Error('foo에서 발생한 에러');
};

const bar = () => {
  foo();
};

const baz = () => {
  bar();
};

try {
  baz();
} catch (err) {
  console.error(err);
}
```

<br>

<br>
<br>

```
> 출처 : 이웅모, 모던 자바스크립트 Deep Dive, 위키북스
```
